import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// eslint-disable-next-line import/order
import './globals.css';
import { ReactNode } from 'react';

import { Header } from '@/components/header';
import { ThemeProvider } from '@/components/theme-provider';
import { TokenRefresher } from '@/components/tokens-refresher';
import { Toaster } from '@/components/ui/toaster';

// eslint-disable-next-line import/order
import { Analytics } from '@vercel/analytics/next';

import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cookies Refresh Example',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <TokenRefresher />

      <head>
        <title></title>
      </head>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased flex flex-col gap-4 px-4',
          inter.className,
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header />
          <main className={'flex justify-center'}>{children}</main>
          <Toaster />
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  );
}
